### ISSUE TITLE
Is it possible to allow for the setting of priorities or weights for workers?

### ISSUE THREAD

**Issue by WSUFan** [buildbarn/bb-remote-execution#113]
It appears that the current logic is to evenly distribute all build requests to the workers. Is it possible to assign specific weights to certain workers?

**Comment by EdSchouten** [comment]
There’s no support for that. What’s your use case?

**Comment by WSUFan** [comment]
Yes, I understand. After reading the code, I noticed that the items in the build queue do not have priority or weight assigned to them. 
In my use case, I have certain workers that are not on dedicated machines, and I would like to reduce the likelihood of using them. I still want to utilize them to some extent because they can provide certain capabilities.

**Comment by EdSchouten** [comment]
It's a hard problem to get right. The reason being that the scheduler currently optimized towards reusing the same workers that were previously used by the same invocation. This means that if Bazel sends a bunch of actions sequentially, then they are virtually guaranteed to get run on the same worker. This is great, because it increases cache hits on input files. What you are proposing is basically an additional (orthogonal) dimension towards which the scheduler should optimize.

One naive way of implementing this would be to replace `invocation.idleSynchronizingWorkers` (type `idleSynchronizingWorkersList`) with a binary heap, sorting idle workers by some kind of weight/priority provided by the worker. But that would only cause it to respect it for the workers within a single invocation. It wouldn't be enforced at a global scale.
