### ISSUE TITLE
Problems Updating Runner to Latest Bazel

### ISSUE THREAD

**Issue by finnball** [buildbarn/bb-remote-execution#12]
As documented [here](https://gitlab.com/remote-apis-testing/remote-apis-testing/issues/15) and solved [here](https://gitlab.com/remote-apis-testing/remote-apis-testing/merge_requests/17) - we needed to update the runner image in order to use bazel 0.25.2 which initially failed.

Buildbarn requires a clean of the temporary directories. The new Ubuntu image supplied by Google contains a folder in `/tmp` which Buildbarn fails to remove on startup. This caused Buildbarn to crash.

For the moment, we [apply a patch](https://gitlab.com/remote-apis-testing/remote-apis-testing/merge_requests/17/diffs?commit_id=eb7b89c14dcaf5d0371ea4d65e4ed85bdf7800c7) to get it working.

**Comment by palvarez89** [comment]
The folder that fails to be cleaned up is `/run/lock`, which contains a `subsys` folder (IIRC) owned by root. It would be good to know why we need to cleanup those folders as it doesn't look like they are ever used when building things.

Could we workaround this issue in a different way?
- Cleanup a subfolder instead of these (if we are actually using them, and we can decide where the temp files go)
- Cleanup only folders we can actually delete (owned by the runner user)
- Don't stop when cleaning up something fails.

**Comment by finnball** [comment]
Thanks for giving more detail there!

> * Don't stop when cleaning up something fails.

I'd disagree with this. I think it should fail though perhaps with a clearer message.

**Comment by ailiev** [comment]
I also had such failures due to a root-owned file/directory under /tmp in my runner container. The file was related to sysdig in Kubernetes. Skipping deletion of files owned by other users seems sensible.

And definitely need better error messages. Locally I modified to `return util.StatusWrap(err, name)` in `RemoveAllChildren`

**Comment by mickael-carl** [comment]
I believe the initial problem has been solved in a5be3f6794281661b4c943577a8dbe979146412b. Now the question is, how to indeed deal with failing cleanup.

**Comment by palvarez89** [comment]
Mind if I ask why the cleanup is needed? Are we expecting builds to put files in those locations?

**Comment by EdSchouten** [comment]
The runner image has been updated in the meantime. Let's mark this as closed.
