### ISSUE TITLE
Any plan to support "bazel test" and "bazel coverage" in the cross-compiling case?

### ISSUE THREAD

**Issue by ling2yt** [buildbarn/bb-remote-execution#136]
We heavily using the buildbarn as our remote execution for bazel.
But we meet the problem to run bazel test and bazel coverage when using the cross-compiling case.
Because it need to compile on the x86 executor and run the test case on the arm executor.

Does the "bazel test" and "bazel coverage" command can do the following step in one command?
1. build test case in x86 execution
2. run test case and generate report on arm execution
3. calculate the coverage using the .gov file on arm or x86 execution
4. sync the test and coverage report to the bazel client

**Comment by EdSchouten** [comment]
Hey @ling2yt,

Buildbarn is merely responsible for running the actions that Bazel creates. Whether that supports cross compiling, test execution and coverage reports fully depends on on Bazel's set of features. Not Buildbarn's.

That said, what you want to do can likely be achieved by calling Bazel with `--extra_execution_platforms=//the/x86/platform,//the/arm/platform --platforms=//the/arm/platform`. This causes your build to target ARM. But during the build it's permitted to use both x86 and ARM. Because x86 is listed first, it will prefer using that one where possible.

If you don't mind, I'm going to close this issue, as there's nothing actionable here on the Buildbarn side. Best regards!

**Comment by ling2yt** [comment]
> --extra_execution_platforms=//the/x86/platform,//the/arm/platform --platforms=//the/arm/platform

We use the `bazel test --remote_excutor` will put the `build and test` to the same executor(one of arm or x86).

Do you mean it can put the build action to the x86 executor and put the test action to the arm executor by calling `bazel test //:arm_testcase --remote_excutor=${x86_executor_addr},${arm_executor_addr} --extra_execution_platforms=//the/x86/platform,//the/arm/platform --platforms=//the/arm/platform`?

**Comment by EdSchouten** [comment]
Let —remote_executor point to a single cluster that has workers for both platforms. Then list both platforms in —extra_execution_platforms.
