### ISSUE TITLE
Make bb-remote-execution go gettable

### ISSUE THREAD

**Issue by henryaj** [buildbarn/bb-remote-execution#19]
Currently this project can't be pulled down with `go get` as the proto definitions aren't built into .go files.

Is it possible to include these files so that non-Bazel users can build this repo?

Thanks,

Henry

**Comment by mickael-carl** [comment]
Hi there! While I get that it can be annoying, at this moment we would prefer to avoid that. It can be quite tedious to keep up-to-date. 
In addition, while this would work for bb-remote-execution, it wouldn't work for instance for [bb-browser](https://github.com/buildbarn/bb-browser/blob/master/cmd/bb_browser/assets/BUILD.bazel), due to the fact that it's not only Go, but also web assets. At one point we could create releases so that one does not need to build bb-* themselves, but we are likely not there yet.
For the time being, can't you simply run protoc yourself to build the proto definitions?
