### ISSUE TITLE
bb_runner caches results with ExitCode != 0

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbarn/bb-remote-execution#31]
An action that run a command that return a non-zero exit code, e.g due to a compile error, is still cached as "OK". In my particular case, the script that would run the action failed to start, and returned 2 as the exit code. 

This causes at least the Goma server (which is what I am using) to think that it received a _current_ build failure. The result is that, without touching/editing some file (multiple in my case), it will not be possible to complete the build.

Relevant code lines:

https://github.com/buildbarn/bb-remote-execution/blob/cfd42310a21e89934034197718ec54b56aad6828/pkg/builder/caching_build_executor.go#L50
https://github.com/buildbarn/bb-remote-execution/blob/cfd42310a21e89934034197718ec54b56aad6828/pkg/builder/local_build_executor.go#L317
https://github.com/buildbarn/bb-remote-execution/blob/cfd42310a21e89934034197718ec54b56aad6828/pkg/environment/local_execution_environment.go#L110

**Comment by EdSchouten** [comment]
Hi @YngveNPettersen,

This is an interesting issue you raise here. This incompatibility/annoyance is due to a small protocol change that has happened over the last year. It used to be the case that the Action Cache was only supposed to hold ActionResult entries for actions that completed successfully (exit_code == 0).

At some point, people started to discuss whether this restriction was smart. There are use cases in which you do want such failures to be cached. The Remote Execution protocol also doesn't document such a restriction in the first place, meaning that Bazel was simply being too strict. Links:

https://github.com/bazelbuild/bazel/issues/7137
https://gitlab.com/BuildGrid/buildgrid/issues/151
https://groups.google.com/forum/#!msg/bazel-discuss/kuRjYFfhDd0/y-Y5nfN1EAAJ

This eventually got resolved by patching up Bazel to allow and ignore such entries:

https://github.com/bazelbuild/bazel/commit/62f54588e6be3d82d21c283350b0131c083b4d8e

It looks like Goma needs to be patched up similarly. Feel free to send a PR to the Goma developers, linking to this issue. I will close this issue for the time being, because I don't think there is anything actionable on the Buildbarn side.
