### ISSUE TITLE
More resilient error handling if bb-runner disappear

### ISSUE THREAD

**Issue by ulrfa** [buildbarn/bb-remote-execution#33]
If a bb-worker disappear, then the remaining bb-workers seems to take over gracefully.

But if a bb-runner has crashed or is not running, then the bb-worker will insist on repeatedly accepting new actions for the unavailable bb-runner, resulting in lots of failed builds.

Would it make sense to try preventing bb-worker from accepting new actions for bb-runners that are not alive? Or handle the ‘connection refused’ error more gracefully?

**Comment by EdSchouten** [comment]
https://github.com/buildbarn/bb-remote-execution/commit/a47313817173e33575ab599b29223cecbcb2f4c6 should already make this a bit easier. There is now a CheckReadiness() call that the worker can call against the runner. It is currently only invoked during worker startup, but it may well be called periodically as well.

**Comment by EdSchouten** [comment]
This should be fixed now. bb_worker will now continuously call CheckReadiness() against the runner when idle, right before it tries to call Synchronize() against the scheduler. When catastrophic failures occur while executing an action (e.g., when bb_runner is down), it will force the scheduler to go idle, so that it's safe to do health checks.

**Comment by ulrfa** [comment]
Thanks @EdSchouten!
